### PR TITLE
Fix uploading YAML file encoding issue on Windows machines

### LINKED ISSUE #688: Upload json form is throwing a 400 error RVL-339
1. Login to web stage: https://web.reveal-stage.smartregister.org/manifest/file-upload
2. Go to admin- releases and click on upload form.
3. Upload a json form.
4. I uploaded a blodd screening json form.
5. Click upload.
6. Observe the error.

image

### PR DESCRIPTION
**Pull request by Rkareko**
Resolves #688

### CODE REVIEW

**Review by githengi — DISMISSED** [review]

File: src/main/java/org/opensrp/web/rest/ClientFormResource.java [hunk 1]
```diff
@@ -218,8 +218,8 @@ private ClientFormMetadata getMostRecentVersion(@NonNull String formIdentifier,
         }
 
         String fileContentType = jsonFile.getContentType();
-        if (!(isClientFormContentTypeValid(fileContentType) || isPropertiesFile(fileContentType, jsonFile.getOriginalFilename()))) {
-            return new ResponseEntity<>("The form is not a JSON/Properties/Yaml file", HttpStatus.BAD_REQUEST);
+        if (!(isClientFormContentTypeValid(fileContentType, jsonFile.getOriginalFilename()) || isPropertiesFile(fileContentType, jsonFile.getOriginalFilename()))) {
+            return new ResponseEntity<>("The form is not a JSON/Properties/Yaml file. The file content type is " + fileContentType, HttpStatus.BAD_REQUEST);
```
Comment (dubdabasoduba) [inline src/main/java/org/opensrp/web/rest/ClientFormResource.java:222]: Is it necessary to show the content type? I understand this is good for debugging but do we need to show it to the users

Comment (Rkareko) [reply src/main/java/org/opensrp/web/rest/ClientFormResource.java]: Updated

**Review by dubdabasoduba — APPROVED** [review]
