### PR TITLE
Json widget validator

### LINKED ISSUE #362: Server side validator should check for validate for the fields defined on the JSON validator files
- [x] The current MVP for this will need the server side validator to check if all the fields marked as `cannot_remove` are available in the uploaded JSON form.

- [x] If any of these fields are missing then the upload should be stopped and the user notified why the upload failed.

### PR DESCRIPTION
**Pull request by ekigamba**
Fixes #362

### CODE REVIEW

File: src/main/java/org/opensrp/web/utils/ClientFormValidator.java [hunk 1]
```diff
@@ -106,4 +111,43 @@ private void initialisePropertiesFileJsonPathReferences() {
...
+        if (formValidator != null && formValidator.getJson() != null && !((String) formValidator.getJson()).isEmpty()) {
+            JsonWidgetValidatorDefinition jsonWidgetValidatorDefinition = objectMapper.readValue((String) formValidator.getJson(), JsonWidgetValidatorDefinition.class);
+            JsonWidgetValidatorDefinition.WidgetCannotRemove widgetCannotRemove = jsonWidgetValidatorDefinition.getCannotRemove();
+            if (widgetCannotRemove != null && widgetCannotRemove.getFields() != null && widgetCannotRemove.getFields().size() > 0) {
+                JsonNode jsonNode = objectMapper.readTree(clientFormContent);
+                fieldsMap.addAll(widgetCannotRemove.getFields());
+
+                Iterator<Map.Entry<String, JsonNode>> iterator = jsonNode.fields();
+                while (iterator.hasNext()) {
+                    Map.Entry<String, JsonNode> jsonFormField = iterator.next();
```
Comment (ekigamba) [inline src/main/java/org/opensrp/web/utils/ClientFormValidator.java:128]: I don't think we need to loop through all the steps & fields in case the `cannot_remove` fields are few in number. Therefore I did not see the need to use the JsonPath expressions which would return all the field keys from all the steps & then we would have to loop through the keys to confirm that required keys are still on the form
